### ISSUE TITLE
Are we keeping this up to date?

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/debian-docker#69]
@dlorenc is this published as gcr.io/google-appengine/debian8?

**Comment by sharifelgamal** [comment]
Yes, this is the source code for gcr.io/google-appengine/debian8. It's released every two week, or whenever there's a new fixed security vulnerability.

**Comment by nkubala** [comment]
Also worth noting that we're mirroring this to `l(auncher).gcr.io/google/debian8`, which is generally what we want non-GAE customers to use.
